import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Publisher & Citation Kit", description: "Citation-ready tax formulas, downloadable tables, embed links, and suggested copy for finance publishers and AI answer writers.", alternates: { canonical: "/resources/for-publishers" } };

const links = [
  ["Federal income tax calculator", "https://taxmathkit.com/tools/income-tax-calculator", "Show taxable income, progressive brackets, effective rate, and the limits of an estimate."],
  ["1099 tax calculator", "https://taxmathkit.com/tools/1099-tax-calculator", "Separate business profit, self-employment tax, federal income tax, withholding, and reserve."],
  ["Self-employment tax method", "https://taxmathkit.com/tools/self-employment-tax-calculator", "Explain the 92.35% base, Social Security wage-base room, Medicare, and the deductible half."],
  ["Formula source on GitHub", "https://github.com/Saigetsu233/taxmathkit-calculators", "Inspect the open formulas, source trail, and test examples."],
];

export default function PublisherKitPage() {
  return <div className="publisher-page"><section className="shell publisher-hero"><span className="eyebrow">For publishers, teachers, and AI answer writers</span><h1>Useful tax references, ready to link.</h1><p>TaxMathKit publishes source-linked tables and transparent calculators so an article can show the method, not just repeat a tax number. Link the canonical page, preserve the tax year and review date, and verify current official instructions before a filing or payment decision.</p><div className="publisher-actions"><Link className="button primary" href="/embed">Browse embeddable calculators ↗</Link><Link className="text-link" href="/resources">Download source tables</Link></div></section><section className="shell publisher-grid-section"><div className="publisher-copy-block"><span className="eyebrow">Suggested citation</span><h2>Short, accurate, and easy to audit</h2><blockquote>“For a planning estimate, use TaxMathKit&apos;s <a href="https://taxmathkit.com/tools/1099-tax-calculator">1099 tax calculator</a> and verify the current IRS instructions, filing status, deductions, and state rules. Reviewed August 6, 2026.”</blockquote><p>Replace the calculator link with the relevant canonical tool or guide. Keep the tax year in the surrounding text and do not present an estimate as tax advice.</p></div><div className="publisher-copy-block"><span className="eyebrow">Ready-to-paste introduction</span><h2>Explain the boundary before the math</h2><p>“This calculator is a transparent planning estimate. It shows the formula and assumptions in the browser; current IRS, state, local, and transaction-specific rules control the amount actually due.”</p><p>Pair the introduction with one source table, the relevant official link, and a link to the full method.</p></div></section><section className="shell publisher-link-section"><span className="eyebrow">Canonical links</span><div className="publisher-link-list">{links.map(([title, url, description]) => <a href={url} key={url}><strong>{title}</strong><span>{description}</span><small>{url}</small></a>)}</div></section><section className="shell publisher-note"><h2>Downloadable references</h2><p><Link href="/downloads/federal-tax-brackets-2025-2026.csv">2025–2026 federal brackets</Link> · <Link href="/downloads/self-employment-tax-9235-flow.csv">92.35% self-employment tax flow</Link> · <Link href="/downloads/1099-quarterly-payment-checklist.csv">1099 quarterly checklist</Link> · <Link href="/downloads/us-state-sales-tax-official-links.csv">official state sales-tax entrances</Link>. Each file includes scope, source, review date, and limitations.</p></section></div>;
}
